### ISSUE TITLE
`exponential!` crashes with some sparse array

### ISSUE THREAD

**Issue by howsiyu** [SciML/ExponentialUtilities.jl#132]
The following code crashes
```julia
using SparseArrays
using ExponentialUtilities

A = sparse([1, 2, 1], [2, 1, 1], [1.0, 2.0, 3.0])
print(exponential!(A, ExpMethodGeneric()))
```
Stepping through a debugger suggests it crashes at `@generated function naivemul!`. Interestingly, everything runs fine if I change A to `sparse([2, 2, 1], [2, 1, 1], [1.0, 2.0, 3.0])`.

**Comment by ChrisRackauckas** [comment]
I'm not sure what this is supposed to mean. You cannot do an in-place matrix exponential on a sparse array since the result is almost certainly dense. We can specialize for LinearAlgebra.Diagonal but for a general sparse matrix the calculation I'm not sure using a sparse matrix in the algorithm is actually an optimization given the result is dense. 

But at least the fix is easy https://github.com/SciML/ExponentialUtilities.jl/pull/135 so we'll probably go with that.
