### ISSUE TITLE
mode=:error_estimate gives wrong results for long times

### ISSUE THREAD

**Issue by axsk** [SciML/ExponentialUtilities.jl#160]
**Describe the bug 🐞**

`expv(t, A, b, mode=:error_estimate)` gives vastly different results for longer time-steps.

**Expected behavior**

I would expect `error_estimate` and `happy_breakdown` results to at least have the same magnitudes

**Minimal Reproducible Example 👇**

```julia
A = I - sprand(100,100,.1) * .1
b = rand(100)
@assert expv(10, A,b) ≈ expv(10, A,b ,mode=:error_estimate)
```

**Error & Stacktrace ⚠️**

```julia
julia>  expv(10, A,b)
100-element Vector{Float64}:
  19372.458459100264
 -57030.13477800453
   3852.973450336655
  -7684.450057227177

julia>  expv(10, A,b ,mode=:error_estimate)
100-element Vector{Float64}:
 -3.1939130045290945e15
  4.314219301303509e15
 -1.6738861310296682e15
 -4.276422508317541e15
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`
```julia
[d4d017d3] ExponentialUtilities v1.25.0
```

  - Output of `versioninfo()`

```julia
julia> versioninfo()
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 64 × AMD EPYC 7502P 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver2)
  Threads: 11 on 64 virtual cores
Environment:
  JULIA_HISTORY = ./.history.jl_
```

**Comment by daviehh** [comment]
It's been a while since I last read through the code, but iirc the error estimation routine only implements the Lanczos algorithm, i.e. mostly for Hermitian (or, in your real-valued case, symmetric) matrices. 

https://github.com/SciML/ExponentialUtilities.jl/blob/18e5161ad28e49e2b92c5f4879495dbd55a0b52e/src/krylov_phiv_error_estimate.jl#L3

https://github.com/SciML/ExponentialUtilities.jl/blob/18e5161ad28e49e2b92c5f4879495dbd55a0b52e/src/krylov_phiv_error_estimate.jl#L86-L101

Note with your example, with a symmetric A `A+=A'` the results do agree w/
```
expv(10, A,b) - expv(10, A,b ,mode=:error_estimate)
```

**Comment by ChrisRackauckas** [comment]
So if you do `:error_estimate` and are non Hermition, we should throw an error saying that it's an inappropriate choice of error estimator?

**Comment by daviehh** [comment]
@ChrisRackauckas Yes, would make sense since it assumes Lanczos/tridagonal KrylovSubspace.H to use with the stegr call

https://github.com/SciML/ExponentialUtilities.jl/blob/18e5161ad28e49e2b92c5f4879495dbd55a0b52e/src/krylov_phiv_error_estimate.jl#L29

correction in PR. Thanks!
